kmer_size: 6
outdir: "output"

fcgr:
  path_tarfile: null
  path_fcgr: 'output/fcgr'
  dir_tarfiles: 'data'

train:
  latent_dim: 100
  epochs: 20  
  batch_size: 16
  architecture: 'CNNAutoencoderCAEBN'
  patiente_early_stopping: 20
  patiente_learning_rate: 15
  train_size: 0.8

kmc:
  max_ram: 4
  tmp: "tmp-kmc"
  threads: 4

seed: 42