kmer_size: 6
outdir: /data/bacteria/experiments/autoencoders

fcgr:
  dir_tarfiles: "/data/bacteria/dataset"
  
train:
  latent_dim: 100
  epochs: 2  
  batch_size: 16
  architecture: 'CNNAutoencoderCAEBN'
  patiente_early_stopping: 20
  patiente_learning_rate: 15
  train_size: 0.8

kmc:
  max_ram: 4
  tmp: "tmp-kmc"
  threads: 4
  min_threshold: 1
  max_threshold: 1000000

seed: 42